version: "3"

services:
  rerum_imperium_backend:
    image: aymericbernard/rerum-imperium-backend:latest
    container_name: rerum_imperium_backend
    restart: always
    environment:
      - VIRTUAL_HOST=rerum-imperium-backend.example.com
      - LETSENCRYPT_HOST=rerum-imperium-backend.example.com
      - LETSENCRYPT_EMAIL=contact@example.com
    networks:
      - proxy

networks:
  proxy:
    external:
      name: nginx-proxy
